[package]
name = "memory-scrubber"
version = "0.1.0"
edition = "2021"

[lib]
name = "memory_scrubber"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
